version: "3.8"
services:
  fitoFit2:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: myPassword123
      POSTGRES_DB: fitofit2
      networks: fitofit2
